# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

House.create(name: "Gryffindor", description: "Gryffindor values bravery, daring, nerve, and chivalry. Its emblematic animal is the lion and its colours are scarlet and gold. Minerva McGonagall was the most recent Head of Gryffindor. Sir Nicholas de Mimsy-Porpington, also known as 'Nearly Headless Nick', was the house ghost. The founder of the house was Godric Gryffindor. Gryffindor corresponds to the element of Fire. The common room was located in one of the highest towers at Hogwarts, the entrance was situated on the seventh floor in the east wing of the castle and is guarded by a portrait of The Fat Lady. She permits entrance if given the correct password, which is changed numerous times throughout the school year. Famous Gryffindors include Albus Dumbledore, Harry Potter, and Celestina Warbeck.")

House.create(name: "Hufflepuff", description: "Hufflepuff values hard work, dedication, patience, loyalty, and fair play. Its emblematic animal is the badger, and Yellow and Black are its colours. Pomona Sprout was the Head of Hufflepuff during 1991-1998, Sprout left the post of Head of Hufflepuff and Herbology Professor sometime before 2017 and her successor for the position of Head of Hufflepuff is currently unknown. The Fat Friar is its ghost. The founder of the house was Helga Hufflepuff. Hufflepuff corresponds to the element of earth. The Hufflepuff dormitories and common room are located somewhere in the basement, near the castle's kitchens. It can be accessed by tapping the barrel two from the bottom, middle of the second row in the rhythm of 'Helga Hufflepuff' and is described as being a cosy and welcoming place with yellow hangings, fat armchairs, and underground tunnels that lead to the dormitories, which have perfectly round doors, similar to barrel tops. Famous Hufflepuffs include Hengist of Woodcroft (founder of Hogsmeade), Newt Scamander, and Artemisia Lufkin (first female minister for magic).")

House.create(name: "Ravenclaw", description: "Ravenclaw values intelligence, knowledge, and wit. Its emblematic animal is the eagle, and its colours are blue and bronze. The Ravenclaw Head of House in the 1990s was Filius Flitwick. The ghost of Ravenclaw is the Grey Lady, who was the daughter of Rowena Ravenclaw, the house's founder. Ravenclaw corresponds to the element of air. The Ravenclaw common room and dormitories are located in a tower on the west side of the castle. Ravenclaw students must answer a riddle as opposed to giving a password to enter their dormitories. This riddle, however, can be answered by non-Ravenclaws. Famous Ravenclaws include Gilderoy Lockheart, Ignatia Wildsmith (inventor of Floo powder), and Garrick Ollivander.")

House.create(name: "Slytherin", description: "Slytherin house values ambition, cunning and resourcefulness and was founded by Salazar Slytherin. Its emblematic animal is the serpent, and its colours are emerald green and silver. Professor Horace Slughorn was the Head of Slytherin during the 1997–1998 school year, replacing Severus Snape, who as well, replaced Slughorn as Potions Professor when he retired for the first time several years prior. The Bloody Baron is the house ghost. The founder of the house was Salazar Slytherin. Slytherin corresponds roughly to the element of water. The Slytherin dormitories and common room are reached through a bare stone wall in the Dungeons. The Slytherin common room lies beneath the Black Lake. It is a long, low underground room with rough stone walls and silver lamps hanging from the ceiling. Famous Slytherins include Merlin, Tom Riddle, and Dolores Umbridge.")

Professor.create(name: "Aurora Sinistra", bio: "Professor Sinistra teaches Astromomy at Hogwarts.", house_id: 2)
Professor.create(name: "Filius Flitwick", bio: "Professor Filius Flitwick was a part-goblin, part-wizard who attended Hogwarts School of Witchcraft and Wizardry and was sorted into Ravenclaw House,[11] being an intelligent young man and a model student.[12] Some time after his graduation, Flitwick returned to Hogwarts and became the Charms Master, as well as the Head of Ravenclaw House.
During the First and Second Wizarding Wars, Flitwick opposed Lord Voldemort. In 1995, he also opposed Dolores Umbridge, the High Inquisitor of Hogwarts, and, in 1997, fought at the Battle of the Astronomy Tower, after which he attended the Funeral of Albus Dumbledore. He also protected the students from the Carrows in the 1997-1998 school year. On 2 May 1998, he partook in the Battle of Hogwarts and defeated many Death Eaters.
He survived the war, and likely continued to teach Charms at Hogwarts to future generations of students.", house_id: 3)
Professor.create(name: "Remus Lupin", bio: "Professor Remus John Lupin, O.M. (First Class), (10 March, 1960 – 2 May, 1998), also known as Moony, was a half-blood wizard and the only son of Lyall and Hope Lupin (née Howell). He was afflicted with lycanthropy during his childhood, as a result of Fenrir Greyback's revenge against Lyall. He attended Hogwarts School of Witchcraft and Wizardry from 1971-1978 and was Sorted into Gryffindor House. During his school years he was one of the Marauders, best friends with Sirius Black, James Potter, and Peter Pettigrew. Together they created the Marauder's Map.", house_id: 1)
Professor.create(name: "Rolanda Hooch", bio: "Madam Rolanda Hooch (b. before 1918) was a witch who worked as the Flying instructor, Quidditch referee, and coach at Hogwarts School of Witchcraft and Wizardry. Madam Hooch likely attended the school as a student and was probably a member of her House's Quidditch team. She learnt to fly on her own Silver Arrow broomstick sometime before or during the Great War and returned to Hogwarts for a job. While on staff at Hogwarts, Hooch worked under Headmasters Albus Dumbledore, Dolores Umbridge, and Minerva McGonagall. She also possibly worked under Armando Dippet and Severus Snape.", house_id: 2)
Professor.create(name: "Pomona Sprout", bio: "Professor Pomona Sprout (b. 15 May[1], 1931 or 1941[1]) was a witch who worked as Head of Hufflepuff House and Head of the Herbology department at Hogwarts School of Witchcraft and Wizardry. She attended the school in her youth, where she was Sorted into Hufflepuff House and excelled at Herbology. Some time after her graduation, Sprout returned to Hogwarts to teach.

Professor Sprout opposed Lord Voldemort during the Second Wizarding War. In 1993, she grew the Mandrakes that would later be used in the Mandrake Restorative Draught to cure those who were petrified by Slytherin's Monster. She also opposed Dolores Umbridge and her tyranny over the school in the 1995-1996 school year, which the rest of the staff were happy to join her in doing, voted for the school to remain open after the Battle of the Astronomy Tower, and assisted in ousting Severus Snape in 1998. Sprout took a group of students to the battlements during the Battle of Hogwarts and threw Devil's Snare and various other dangerous plants onto the invading Death Eaters.

She ultimately survived the War. By 2014, Neville Longbottom taught Herbology, either alongside her or as a replacement.", house_id: 2)
Professor.create(name: "Cuthbert Binns", bio: "Professor Cuthbert Binns was a wizard and History of Magic professor at Hogwarts School of Witchcraft and Wizardry. He owned an office in the main castle and Classroom 4F on the first floor to teach in. He taught until a very old age, when he fell asleep in the staff room and died in slumber. Now, he is a ghost who continued to teach, droning on about various Goblin Rebellions and Giant Wars to bored, sleeping students.

Professor Binns's lessons were regarded as some of the most boring at Hogwarts, and only once in known history did he talk about something not strictly factual. During the 1991–1992 school year, he taught his first year students about numerous historical personalities such as Uric the Oddball and Emeric the Evil, whom the class always got confused with. The following academic year, he relayed the legend of the Chamber of Secrets to his second year class, but only after every student in the class showed complete and utter interest, despite initially stating the legend of the Chamber to be unimportant. He continued to teach Harry Potter and his class for three further years, until most, if not every one of his students dropped History of Magic.", house_id: 3)
Professor.create(name: "Severus Snape", bio: "Professor Severus Snape (9 January, 1960 – 2 May, 1998) was a half-blood wizard serving as Potions Master (1981-1996), Defence Against the Dark Arts professor (1996-1997), and Headmaster (1997-1998) of the Hogwarts School of Witchcraft and Wizardry as well as a member of the Order of the Phoenix and a Death Eater. His double life played an extremely important role in both of the Wizarding Wars against Voldemort. The only child of Muggle lowlife Tobias Snape and Gobstones witch Eileen Snape (née Prince), Severus was raised in the Muggle dwelling of Spinner's End, which was in close proximity to the home of the Evans family, though in a poorer area. He met Lily and Petunia Evans when he was nine and fell deeply in love with Lily, becoming a close friend of hers. ", house_id: 4)
Professor.create(name: "Minerva McGonagall", bio:"Professor Minerva McGonagall, O.M. (First Class), (b. 4 October, 1935) was a half-blood witch, the only daughter of Muggle Robert McGonagall and witch Isobel Ross. She had two younger brothers, Malcolm and Robert Jr. Minerva was a registered Animagus who attended Hogwarts School of Witchcraft and Wizardry from 1947-1954 and was Sorted into Gryffindor House (but it took the sorting hat 5 ½ minutes to decide if she was Gryffindor or Ravenclaw, therefore making her a Hatstall).

After her education, Minerva worked for two years at the Ministry of Magic and later returned to Hogwarts, where she became Head of Gryffindor House, Transfiguration professor and concurrently, at differing times, Deputy Headmistress and Headmistress of Hogwarts.", house_id: 1)
Professor.create(name: "Septima Vector", bio: "Professor Septima Vector (fl. 1974 – 1996) was a witch and Professor of Arithmancy at Hogwarts School of Witchcraft and Wizardry from at least the 1991–1992 school year. She may have also been the Advanced Arithmancy Studies teacher.

Professor Vector was known among students as a 'really strict' teacher, so much so that some pupils were unsure whether to take her classes. She was also known for giving her pupils plenty of complicated homework. Her subject was Hermione Granger's favourite subject while she was in school, but one of her roommates did not like it because she found it too difficult.", house_id: 3)
Professor.create(name: "Rubeus Hagrid", bio:"Professor Rubeus Hagrid (b. 6 December 1928) was a half-giant wizard, son of Mr Hagrid and the giantess Fridwulfa, and elder half-brother of the giant Grawp.

Hagrid attended Hogwarts School of Witchcraft and Wizardry in 1940 and was sorted into Gryffindor house. In Hagrid's third year, he was framed by Tom Riddle for the crime of opening the Chamber of Secrets and using his pet Acromantula to attack several Muggle-born students and eventually killing one of them. Though Hagrid's wand was snapped and he was expelled, he was trained as gamekeeper of Hogwarts and allowed to live on the school grounds at the request of Albus Dumbledore.", house_id: 1)
Professor.create(name: "Sybill Trelawney", bio: "Professor Sybill Patricia Trelawney (b. 9 March, pre 1962) was a half-blood witch and professor of Divination at Hogwarts School of Witchcraft and Wizardry. She is the great-great-granddaughter of the celebrated Cassandra Trelawney, who was also a Seer.", house_id: 3)

Professor.create(name: "Charity Burbage", bio: "Professor Charity Burbage (d. July, 1997) was the Professor of Muggle Studies at Hogwarts School of Witchcraft and Wizardry, after the departure of the wizard who formerly held the post. Her career lasted from 1993 to 1997.

She believed that Muggles were not so different from wizards and witches, and used this viewpoint in her teaching. It would eventually lead to her death as Lord Voldemort murdered her personally for writing a Daily Prophet article about her views during the Second Wizarding War.", house_id: 1)
Professor.create(name: "Bathsheda Babbling", bio: "Professor Bathsheda Babbling was a witch and professor of Study of Ancient Runes and possibly Ancient Studies at Hogwarts School of Witchcraft and Wizardry.", house_id: 3)
Professor.create(name: "Wilkie Twycross", bio: "Wilkie Twycross (b. before 1979) was an employee of the Ministry of Magic who was the Apparition Instructor at Hogwarts School of Witchcraft and Wizardry to students who are age seventeen or approaching age seventeen and wish to obtain a licence to Apparate.", house_id: 4)


Subject.create(name: "Astronomy", description: "Astronomy is the only field of study at Hogwarts that has a direct equivalent in the Muggle world. Astronomy classes take place in the Astronomy Tower, the tallest tower in Hogwarts, and are taught by Professor Aurora Sinistra. Lessons involve observations of the night skies with telescopes. Lessons are held every week at midnight, and first years have lessons on Wednesday. Known student homework activities include learning the names of stars, constellations and planets, and their location, movements, and environments.", professor_id: 1)
Subject.create(name: "Charms", description: "Charms is the type of spells concerned with giving an object new and unexpected properties, and hence this class mainly consists on learning those sorts of spells. Charms classes are described as notoriously noisy and chaotic, as the lessons are largely practical. Many of the exposition sequences in the books are set in Charms classes, which are on the second floor of Hogwarts.", professor_id: 2)
Subject.create(name: "Defence Against the Dark Arts", professor_id: 3, description: "Defence Against the Dark Arts (sometimes written as DADA) is a subject taught at Hogwarts School of Witchcraft and Wizardry and Ilvermorny School of Witchcraft and Wizardry. In this class students learn how to magically defend themselves against Dark Creatures, the Dark Arts, and other dark charms. Offensive magic is also taught in this class, such as how to duel, which requires the use of both offensive and defensive magic. The subject is the core class at Hogwarts. The position of Defence Against the Dark Arts professor here was once rumoured to be jinxed, as no teacher could hold the post for more than a year. Tom Marvolo Riddle jinxed the position because Dumbledore did not give him the job when he applied for it. The fact that no teacher has lasted longer than a year meant that the subject has had numerous Professors. Ilvermorny began teaching the subject in the 17th century. Also Harry Potter would occasionally deliver Defence Against the Dark Arts lectures at Hogwarts.")

Subject.create(name: "Flying", professor_id: 4, description: "Flying is the class that teaches the use of broomsticks made for the use of flying and is taught only to Hogwarts first years by Rolanda Hooch. The subject is the only one that requires physicality.")


Subject.create(name: "Herobology", professor_id: 5, description: "Herbology is the study of magical plants and how to take care of, utilise and combat them. There are at least three greenhouses, holding a variety of magical plants of varying degrees of lethality. Herbology is also the subject Neville Longbottom excels in. He later replaces Professor Sprout as the Herbology teacher.")
Subject.create(name: "History of Magic", professor_id: 6, description: "History of Magic is the study of magical history. Cuthbert Binns' lessons are depicted as some of the most boring at Hogwarts. They are only lectures, given without pause, about significant events in wizarding history. Topics have included Goblin Rebellions, Giant wars, and the origins of wizarding secrecy. This is the only class at Hogwarts that is taught by a ghost, as the professor never noticed he had died and simply continued teaching as if nothing had changed.")
Subject.create(name: "Potions", professor_id: 7, description: "Potions is described as the art of creating mixtures with magical effects. It requires the correct mixing and stirring of ingredients at the right times and temperatures. Snape's lessons are depicted as unhappy, oppressing times set in a gloomy dungeon in the basement of the castle, whilst Horace Slughorn's, who replaces Severus Snape as Potions Master, is shown as more cheerful and even fun at times.")
Subject.create(name: "Transfiguration", professor_id: 8, description: "Transfiguration is the art of changing the form or appearance of an object, and hence this is what this class teaches. Transfiguration is a theory-based subject, including topics such as 'Switching Spells' (altering only a part of some object, such as giving a human rabbit's ears); Vanishing Spells (causing an object to completely disappear); and Conjuring Spells (creating objects out of thin air). It is possible to change inanimate objects into animate ones and vice versa — Minerva McGonagall, the class's teacher, transfigures her desk into a pig.")
Subject.create(name: "Arithmancy", professor_id: 9, description: "Arithmancy is a branch of magic concerned with the magical properties of numbers. It is a favourite subject of Hermione Granger. Arithmancy is reportedly difficult, as it requires memorising or working with many charts. It is also an elective course, that can be taken by students third year and above. The subject is taught by Professor Septima Vector. It is separated into normal Arithmancy and Advanced Arithmancy Studies")
Subject.create(name: "Care of Magical Creatures", professor_id: 10, description: "Care of Magical Creatures is the class which instructs students on how to care for magical beasts. Classes are held outside the castle. In Harry's first two years, the class is taken by Professor Silvanus Kettleburn who then retires 'in order to enjoy more time with his remaining limbs'. Dumbledore then recruits the gamekeeper Rubeus Hagrid to accept a teaching position along with his gamekeeping duties. Although Hagrid is obviously very experienced and knowledgeable, he consistently misjudges the risk that the animals he uses in his lessons pose to his students, which sometimes results in chaos. When Hagrid is absent, his lessons are taken over by Professor Grubbly-Plank, a witch and acquaintance of Dumbledore's.")
Subject.create(name: "Divination", professor_id: 11, description: "Divination is the art of predicting the future. Various methods are described, including tea leaves, Fire-omens, Crystal balls, Palmistry, Cartomancy (including the reading of conventional playing cards and the tarot), astrology, and Dream interpretations. Divination is described by Professor McGonagall as 'one of the most imprecise branches of magic'. Supporters of the subject claim that it is an inexact science that requires innate gifts like the 'Inner Eye'. Those opposed claim that the subject is irrelevant and fraudulent. Harry is first taught Divination by Professor Trelawney, and then later by Firenze after Trelawney is sacked by Dolores Umbridge in Harry's fifth year. In the sixth (and presumably seventh) year, Firenze and Professor Trelawney teach Divination.")

Subject.create(name: "Muggle Studies", professor_id: 12, cd pottedescription: "Muggle Studies is a class taught by Charity Burbage which involves the study of the Muggle (non-magical) culture 'from a wizarding point of view.' It also includes Muggle Art and Muggle Music. The only need for witches and wizards to learn about Muggle ways and means is to ensure they can blend in with Muggles while needing to do so (for example, at the 1994 Quidditch World Cup). As the class is only mentioned as being taken by Hermione, and for just one year, little is known about its curriculum.")

Subject.create(name: "Ancient Runes", professor_id: 13, description: "The Study of Ancient Runes is a general theoretical subject that studies ancient runic scripts. It is taught by Professor Bathsheda Babbling. It is an elective course, that can be taken by students third year and above.")
Subject.create(name: "Apparition", professor_id: 14, description: "Apparition is the magical form of teleportation in the wizarding world. Lessons are optional to those in the sixth and seventh years. In the wizarding world, performing Apparition requires a licence and may only be legally performed by people over seventeen years of age. The described reason for the restriction is that Apparition is dangerous if done improperly: insufficient concentration may lead to body parts being left behind in an unfortunate side-effect known as splinching. Although, as Hermione points out innumerable times throughout the series, magical enchantments on Hogwarts Castle and grounds prevent Apparition and Disapparition inside the castle, these protections are temporarily relaxed within the Great Hall for short periods to permit students to practise Apparition. Wilkie Twycross, a Ministry of Magic Apparition Instructor, offers lessons in Apparition to sixth-years.")



Patronu.create(name: "Stag")
Patronu.create(name: "Jack Russell Terrier")
Patronu.create(name: "Otter")
Patronu.create(name: "House")
Patronu.create(name: "Hungarian Horntail")
Patronu.create(name: "Rabbit")
Patronu.create(name: "Hare")
Patronu.create(name: "Phoenix")
Patronu.create(name: "Blue Eyes White Dragon")
Patronu.create(name: "Chinese Fireball")
Patronu.create(name: "Leech")
Patronu.create(name: "Termite")
Patronu.create(name: "King Cobra")
Patronu.create(name: "R2D2")
Patronu.create(name: "Golem")
Patronu.create(name: "Marju")
Patronu.create(name: "Blobfish")
